_wandb:
    value:
        cli_version: 0.21.4
        e:
            ujghnoh4ex4u2xu3vp14sh1rwcow82el:
                codePath: train_diffusion.py
                codePathLocal: train_diffusion.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1000186310656"
                        used: "933592875008"
                email: bryars@hotmail.com
                executable: D:\git\lerobot-scratch\venv\Scripts\python.exe
                git:
                    commit: 3bb44419903f8275a2488d3fbfd8b558edf4ea3c
                    remote: git@github.com:DanielBryars/lerobot-scratch.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-a7a207c3-0758-e34f-cc75-1ea3e42f9e0f
                host: SHED
                memory:
                    total: "68318273536"
                os: Windows-11-10.0.26200-SP0
                program: D:\git\lerobot-scratch\train_diffusion.py
                python: CPython 3.13.2
                root: D:\git\lerobot-scratch
                startedAt: "2025-11-27T18:53:47.650131Z"
                writerId: ujghnoh4ex4u2xu3vp14sh1rwcow82el
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.2
            "5": 0.21.4
            "6": 4.51.3
            "8":
                - 3
            "12": 0.21.4
            "13": windows-amd64
batch_size:
    value: 64
crop_shape:
    value:
        - 84
        - 84
dataset_episodes:
    value: 50
dataset_fps:
    value: 5
dataset_frames:
    value: 2837
horizon:
    value: 16
learning_rate:
    value: 0.0001
n_action_steps:
    value: 8
n_obs_steps:
    value: 2
noise_scheduler_type:
    value: DDPM
num_train_timesteps:
    value: 100
num_workers:
    value: 0
total_params:
    value: 266622758
trainable_params:
    value: 266622758
training_steps:
    value: 50000
vision_backbone:
    value: resnet18
