_wandb:
    value:
        cli_version: 0.21.4
        e:
            cw8j15v1db1olcgbxqih51f5qcs3to7d:
                args:
                    - --image-size
                    - "224"
                    - --steps
                    - "50000"
                    - --chunk-size
                    - "16"
                codePath: train_act.py
                codePathLocal: train_act.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1000186310656"
                        used: "951029493760"
                email: bryars@hotmail.com
                executable: D:\git\lerobot-scratch\venv\Scripts\python.exe
                git:
                    commit: 92c6951ae344edca13bf1ded6529901d63c55054
                    remote: git@github.com:DanielBryars/lerobot-scratch.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-a7a207c3-0758-e34f-cc75-1ea3e42f9e0f
                host: SHED
                memory:
                    total: "68318273536"
                os: Windows-11-10.0.26200-SP0
                program: D:\git\lerobot-scratch\train_act.py
                python: CPython 3.13.2
                root: D:\git\lerobot-scratch
                startedAt: "2025-11-28T22:34:29.481796Z"
                writerId: cw8j15v1db1olcgbxqih51f5qcs3to7d
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 16
            "4": 3.13.2
            "5": 0.21.4
            "6": 4.51.3
            "8":
                - 3
            "12": 0.21.4
            "13": windows-amd64
batch_size:
    value: 64
chunk_size:
    value: 16
dataset_episodes:
    value: 50
dataset_fps:
    value: 5
dataset_frames:
    value: 2837
dim_model:
    value: 512
kl_weight:
    value: 10
learning_rate:
    value: 1e-05
n_action_steps:
    value: 16
n_obs_steps:
    value: 1
num_workers:
    value: 0
total_params:
    value: 51554182
trainable_params:
    value: 51554182
training_steps:
    value: 50000
use_vae:
    value: true
vision_backbone:
    value: resnet18
